services:
  node-typescript-template-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    image: node-typescript-template:latest
    container_name: node-typescript-template
    ports:
      - "0.0.0.0:8080:8080"

  node-typescript-template-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: node-typescript-template:dev
    container_name: node-typescript-template-dev
    volumes:
      - .:/app
      - node-modules:/app/node_modules
    ports:
      - "0.0.0.0:8080:8080"

  node-typescript-template-dev-container:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-container
    image: node-typescript-template:dev-container
    container_name: node-typescript-template-dev-container
    volumes:
      - .:/app
      - node-modules:/app/node_modules
    ports:
      - "0.0.0.0:8080:8080"
    tty: true

volumes:
  node-modules:
