x-common-properties: &common
  ports:
    - 0.0.0.0:8080:8080

x-dev-properties: &dev
  volumes:
    - .:/app
    - node-modules:/app/node_modules

services:
  prod:
    <<:
      - *common
    build:
      target: prod
    image: node-typescript-template:latest
    container_name: node-typescript-template

  dev:
    <<:
      - *common
      - *dev
    build:
      target: dev
    image: node-typescript-template:dev
    container_name: node-typescript-template-dev

  dev-container:
    <<:
      - *common
      - *dev
    build:
      target: dev-container
    image: node-typescript-template:dev-container
    container_name: node-typescript-template-dev-container
    tty: true

volumes:
  node-modules:
