on:
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Restore npm cache
        id: npm-cache-restore
        uses: actions/cache/restore@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Save npm cache
        uses: actions/cache/save@v3
        with:
          path: ~/.npm
          key: ${{ steps.npm-cache-restore.outputss.cache-primary-key }}

      - name: Run ${{ matrix.job }} tasks
        run: npm run ${{ matrix.job }}

  health-check:
    needs: code-quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [prod, dev]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker BuildKit
        uses: docker/setup-buildx-action@v2

      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
        run: docker build -t node-typescript-template --target ${{ matrix.environment }} .

      - name: Create container
        run: docker create -p 8080:8080 --name api node-typescript-template

      - name: Import project files into container
        if: matrix.environment == 'dev'
        run: docker cp . api:/app

      - name: Start container
        run: docker start api

      - name: Run health-check
        run: docker exec api node scripts/health-check.js http://0.0.0.0:8080/healthz 10 5
