on:
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Run ${{ matrix.job }} tasks
        run: npm run ${{ matrix.job }}

  health-check:
    needs: unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [prod, dev]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build image
        run: docker build -t node-typescript-template --target ${{ matrix.environment }} .

      - name: Run health-check
        run: |
          docker run -d -v $PWD:/app -p 8080:8080 --name api node-typescript-template
          docker exec api node scripts/health-check.js http://0.0.0.0:8080/healthz 10 5
