on:
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [lint, test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Restore npm cache
        id: npm-cache-restore
        uses: actions/cache/restore@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci

      - name: Save npm cache
        uses: actions/cache/save@v3
        with:
          path: ~/.npm
          key: ${{ steps.npm-cache-restore.outputs.cache-primary-key }}

      - run: npm run ${{ matrix.job }}

  health-check:
    needs: code-quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [prod, dev]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v2
        id: image-builder
        with:
          context: .
          target: ${{ matrix.environment }}
          load: true
          cache-from: type=gha,scope=${{ github.repository }}
          cache-to: type=gha,mode=max,scope=${{ github.repository }}

      - run: docker create -p 8080:8080 --name api ${{ steps.image-builder.outputs.imageid }}

      - name: Import project files into container
        if: matrix.environment == 'dev'
        run: docker cp . api:/app

      - run: docker start api

      - name: Run health-check
        run: docker exec api node scripts/health-check.js http://0.0.0.0:8080/healthz 10 5
