name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build image
        run: docker build -t forvais/node-typescript-template --target dev .

      - name: Save Docker image
        run: docker save forvais/node-typescript-template > image.tar

      - name: Upload Docker image artifact
        uses: action/upload-artifact@v3
        with:
          name: docker-image
          path: image.tar
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v3
        with:
          name: docker-image

      - name: Import Docker image
        run: docker load < image.tar

      - name: Run Tests
        run: docker run forvais/node-typescript-template \
              npm run lint
  unit:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v3
        with:
          name: docker-image

      - name: Import Docker image
        run: docker load < image.tar

      - name: Run Tests
        run: docker run forvais/node-typescript-template \
              npm run test

  health-check:
    needs: unit
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v3
        with:
          name: docker-image

      - name: Import Docker image
        run: docker load < image.tar

      - name: Run Tests
        run: docker run forvais/node-typescript-template \
              node scripts/health-check.js http://0.0.0.0:8080 10 5
