name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build image
        run: docker build -t forvais/node-typescript-template --target dev .

      - name: Save Docker image
        run: docker save forvais/node-typescript-template > image.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: image.tar
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Docker image
        uses: actions/download-artifact@v3
        with:
          name: docker-image

      - name: Import Docker image
        run: docker load < image.tar

      - name: Install Node dependencies
        run: docker run -v $PWD:/app forvais/node-typescript-template npm ci

      - name: Lint source files
        run: docker run -v $PWD:/app forvais/node-typescript-template npm run lint
  unit:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Docker image
        uses: actions/download-artifact@v3
        with:
          name: docker-image

      - name: Import Docker image
        run: docker load < image.tar

      - name: Install Node dependencies
        run: docker run -v $PWD:/app forvais/node-typescript-template npm ci

      - name: Run unit tests
        run: docker run -v $PWD:/app forvais/node-typescript-template npm run test

  health-check:
    needs: unit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Docker image
        uses: actions/download-artifact@v3
        with:
          name: docker-image

      - name: Import Docker image
        run: docker load < image.tar

      - name: Install Node dependencies
        run: docker run -v $PWD:/app forvais/node-typescript-template npm ci

      - name: Run health-check
        run: |
          docker run -d -v $PWD:/app -p 8080:8080 forvais/node-typescript-template --name api
          docker exec -it api node scripts/health-check.js http://0.0.0.0:8080/healthz 10 5
